sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/chrome .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: Xun/VNQu6hZFO8hitGXsJoj6eqmDRWl98UbrVjNlCEOZDTtAC8rmHfiuqfbgpYVbhDMeD/Zdhxs8bZvVcKm73L5Gww/25Q5Sn6i3irtW00i3t1qqSKYYZU8+0OdWWGKBeTkey9NYW1tf5S5eKgI6ffILVOdUPNSHsUqt/WLF1nxzBJgjUoyN2Rp669ohmjNryv1LtGeJtSfjTAx4jIJ2g2zH9y6puC6VS469MzbGlIHsPICWeX3cVmbQuGrCWsCBSRlwlIqPOWxWg0HIkrQ9nW75CnrK/EaaFxmemtaJ72UO+SU7KmnR9QWUVfE5avNXCN4HQXw/mRo8yeecYFj1cCxxUgzx8lHBGhFR8vHCS5TaAQPjOaSZ9y3c3JRgRgG4zqmewFUOTsv2jAYm72uvO6XXnl3SypsPUv5c1Or8+90hVzXz5BgralKXUTQFVx6LQqKTOsOinja1NGJv98jRPWLqxmBNAHg++ziaCLOBbU0bmT71v1X7AP/5kSvHo4jgsCZ3qKGohvUjZ5pBfoxJ+dHriS3gOLMsreCPzvIeH7KaBPl3iIZBGp3KqKgmXV0UlqP+CPjjXj2fudusCAuT07WXIy7J+dnd7m5dXs0xTQ/xVOa10E22iSwUKjD4TOJM/oYQUkUG+lPL94Sy81z7xnPmCxI0g0lMLNd5bBgLnb0=
  - secure: P6A8yjE6+K8GW7cyQvsjPv7r4qobsAl8y0SLWUQgFHJcXO1eY4uH4CCo8uAxmRM52+zccdsSgOoQjcrCQsUK6zYCObLFg6tnJXzmBjRhfozOjFo1bDTJ4LMCTO/9fQCgMMtvq5UEf3OXG6ARq3XRHvm8Vk9L2u1WKR/BW7THng6LzZm3Hn9wyBJdnxQQ4L1VQxO5WRI9Z9i3On6kMQc/vqdtscOfDv2GFTC9q3qN4XK5IaesBU209st3/03Tq+mWvSSZg8jH0bxW0o1gZhbR6NsSiTRhBk9+Eal64JEp9INMHKX1rZ1GyvgPs4MgJIliAF2ZJYp0xSkpaGLqdkR8pTYOaz1B41kUCrzYacrzP/VyzfiuK+fN4wJjeVxMkFo2Qc/MRhjho8tSvTPcopQPpRiyIJ9K4WmaqGgZ2EzblqKLRUpp/WWEqfaL7HrcvO/lfsDf0A6bmpZlPYUN+DZXp2qunP80KEmwscpia+CWIdH9UUtdkH7XZVAoP0AvCnQ6/lNn94wlmok4rOn5Sp4r7oEWtJHctsL2M+ql8LdSboe710De3epNhl50RSDqHVPK8unqC3hz9+gH1GyF6OBuEQHH1GRe/yX34C0SR9CNUCpECsswBCcRQZR/Dch2MfjJiScXjbKsjqXQO6BvfBR2oEvPnf6UF0HhhaLMoK3ekP4=
