name: Docker Image CI

on:
  push:
    branches: [master]
    tags:
      - 1.*
  pull_request:
    branches: [master]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: REF_TYPE
        run: echo ${{ env.GITHUB_REF_NAME }}

      - name: Build only
        if: ${{ env.GITHUB_REF_TYPE != 'tag' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: jinwuzhao/chrome:latest

      - name: Login to DockerHub
        if: ${{ env.GITHUB_REF_TYPE == 'tag' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.GITHUB_REF_TYPE == 'tag' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jinwuzhao/chrome:latest,jinwuzhao/chrome:${{ env.GITHUB_REF_NAME }}
