name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: ${{ env.GITHUB_REF_TYPE == 'tag' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ env.GITHUB_REF_TYPE == 'tag' }}
          tags: 
            - jinwuzhao/chrome:latest
            - jinwuzhao/chrome:${{ env.GITHUB_REF_NAME }}
